DROP TABLE IF EXISTS raw_messages;
DROP TABLE IF EXISTS fact_links;
DROP TABLE IF EXISTS facts;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS api_keys;
DROP TABLE IF EXISTS accounts;
DROP EXTENSION IF EXISTS vector;
