DROP TABLE IF EXISTS facts CASCADE;
DROP TABLE IF EXISTS sources CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS threads CASCADE;
DROP TABLE IF EXISTS agents CASCADE;
DROP TABLE IF EXISTS api_keys CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;

DROP EXTENSION IF EXISTS vector;