DROP TABLE IF EXISTS facts;
DROP TABLE IF EXISTS sources;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS agents;
DROP TABLE IF EXISTS api_keys;
DROP TABLE IF EXISTS accounts;
DROP EXTENSION IF EXISTS vector;
